
#https://github.com/jtudelag/ansible-ee-gitops/tree/v0.2
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ansible-builder
  namespace: ansible-ee-build
spec:
  workspaces:
  - name: ee-repo
  params:
  # Fetch Task
  - name: git-url
    type: string

    description: url of the git repo for the code of deployment
    default: https://github.com/mmayeras/ee-build-demo.git

  - name: git-revision
    type: string
    description: revision to be used from repo of the code for deployment (Commit id)
    default: main

  # ansible-builder task
  - name: ANSIBLE_BUILDER_IMAGE
    description: The location of the ansible-builder image.
    type: string
    default: registry.redhat.io/ansible-automation-platform-24/ansible-builder-rhel9:latest

  - description: Name of the container image to be built
    name: NAME
    type: string

  - description: Tag of the container image to be built
    name: TAG
    type: string
    default: "latest"

  # Buildah task
  - description: Path to the directory to use as context for buildah.
    name: CONTEXT
    type: string
    default: "context/"

  - description: The path to the Dockerfile to execute.
    name: DOCKERFILE
    type: string
    default: "Containerfile"

  - description: buildah build Args
    name: BUILD_ARGS
    type: string
    default: ""

  - description: buildah push Args
    name: PUSH_ARGS
    type: string
    default: ""

  - description: Verify the TLS on the registry endpoint (for push/pull to a non-TLS registry)
    name: TLSVERIFY
    type: string
    default: "false"

  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
      - name: output
        workspace: ee-repo
      params:
      - name: url
        value: $(params.git-url)
      - name: deleteExisting
        value: "true"
      - name: revision
        value: $(params.git-revision)

    - name: ansible-builder-create
      taskRef:
        name: ansible-builder
        kind: Task
      workspaces:
      - name: source
        workspace: ee-repo
      runAfter:
      - fetch-repository
      params:
      - name: BUILDER_IMAGE
        value: $(params.ANSIBLE_BUILDER_IMAGE)

    - name: build-image-tag
      taskRef:
        name: buildah
        kind: ClusterTask
      workspaces:
      - name: source
        workspace: ee-repo
      runAfter:
      - ansible-builder-create
      params:
      - name: TLSVERIFY
        value: "false"
      - name: IMAGE
        value: $(params.NAME):$(params.TAG)
      - name: CONTEXT
        value: "$(params.CONTEXT)"
      - name: DOCKERFILE
        value: "$(params.DOCKERFILE)"
      - name: BUILD_EXTRA_ARGS
        value: "$(params.BUILD_ARGS)"
      - name: PUSH_EXTRA_ARGS
        value: "$(params.PUSH_ARGS)"

    - name: build-image-latest
      taskRef:
        name: buildah
        kind: ClusterTask
      workspaces:
      - name: source
        workspace: ee-repo
      runAfter:
      - ansible-builder-create
      params:
      - name: TLSVERIFY
        value: "false"
      - name: IMAGE
        value: $(params.NAME):latest
      - name: CONTEXT
        value: "$(params.CONTEXT)"
      - name: DOCKERFILE
        value: "$(params.DOCKERFILE)"
      - name: BUILD_EXTRA_ARGS
        value: "$(params.BUILD_ARGS)"
      - name: PUSH_EXTRA_ARGS
        value: "$(params.PUSH_ARGS)"