---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: openshift-storage-operatorgroup
  namespace: openshift-storage
  spec:
    targetNamespaces:
    - openshift-storage
    upgradeStrategy: Default