apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata: 
  name: lvmcluster-sample
  namespace: openshift-storage
spec:
  storage:
    deviceClasses:
    - name: vg1
      thinPoolConfig:
        name: thin-pool-1
        overprovisionRatio: 10
        sizePercent: 90