---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: import
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements: 
      - name: sno-home
  template:
    metadata:
      name: import-{{name}}
      labels:
        velero.io/exclude-from-backup: "true"
    spec:
      project: policies
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/mmayeras/gitops-demo.git
        targetRevision: main
        path: XaC/2-import
      destination:
        server: https://kubernetes.default.svc