---
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: demo

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo
  namespace: ansible-automation-platform

--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-demo
  namespace: demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: demo
  namespace: ansible-automation-platform