---
apiVersion: v1
kind: Secret
metadata:
  namespace: ansible-automation-platform
  name: ocp-bearer-secret
  annotations:
    kubernetes.io/service-account.name: demo
type: kubernetes.io/service-account-token

---
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleCredential
metadata:
  name: ocp-bearer-secret
  namespace: ansible-automation-platform
spec:
  name: OCP Demo Cluster
  organization: Default
  connection_secret: admin-token
  description: "Bearer Credential"
  type: "OpenShift or Kubernetes API Bearer Token"
  kubernetes_api: https://api.compact.lab.mmayeras.fr:6443
  kubernetes_bearer_token_secret: ocp-bearer-secret
  runner_pull_policy: IfNotPresent
