---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
resources:
- 0-aap-project.yml
- 1-aap-admin-token.yml
- 2-ocp-demo-project.yml
- 3-aap-template-hellow.yml
- 4-aap-template-ocp-sample-app.yml
- 5-aap-template-ocp-customize-app.yml
- 6-aap-template-create-templates.yml
- 7-aap-ocp-credential.yml