apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata: 
  name: lvmcluster
  namespace: openshift-storage
spec:
  storage:
    deviceClasses:
    - deviceSelector:
        paths:
        - /dev/sda
      fstype: xfs
      name: vg1
      thinPoolConfig:
        name: thin-pool-1
        overprovisionRatio: 10
        sizePercent: 90
