---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: lvm-operator
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - cluster: local
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: openshift-storage-lvm-{{cluster}}
    spec:
      project: demo
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/mmayeras/gitops-demo.git
        targetRevision: dev
        path: XaC/0-lvm
      destination:
        server: "{{url}}"