---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

resources:
  - openshift-gitops.yaml
  - openshift-gitops-apps.yaml
  - aap.yaml
  - openshift-pilelines.yaml
  - aap-build-pipeline.yaml
  