---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: acm-gitops-integration
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements: 
      - name: in-cluster 
  template:
    metadata:
      name: acm-gitops-integration-{{name}}
    spec:
      project: advanced-cluster-management
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/mmayeras/gitops-demo.git
        targetRevision: main
        path: XaC/3-acm-gitops-integration
      destination:
        server: https://kubernetes.default.svc