apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ansible-builder-pvc
  namespace: ansible-ee-build
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: lvms-vg1
