---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
resources:
- 0-mclset.yml
- 1-mclsetbinding.yml
- 2-placement.yml
- 3-gitopscluster.yml